-- Moodot RDS PostgreSQL schema draft
-- ------------------------------------------------------------
-- This is a draft based on the current backend/worker code.
-- Before applying it to RDS, compare it with the real Supabase
-- schema exported from information_schema.

create extension if not exists pgcrypto;

create table if not exists public.emotion_categories (
  emotion_id integer generated by default as identity primary key,
  emotion varchar not null unique
);

create table if not exists public.memories (
  id bigserial primary key,
  user_id text not null,
  title text,
  text text,
  text_ciphertext text,
  text_iv text,
  text_key_version smallint not null default 1,
  image_url text,
  emotion_id integer not null references public.emotion_categories(emotion_id),
  with_whom text,
  location_lat double precision,
  location_lng double precision,
  location_label text,
  place_name text,
  location_type text,
  memory_at timestamptz,
  processed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  title text not null,
  note text,
  location text,
  start_date date,
  end_date date,
  cover_memory_id bigint references public.memories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collection_memories (
  collection_id uuid not null references public.collections(id) on delete cascade,
  memory_id bigint not null references public.memories(id) on delete cascade,
  position integer not null default 0,
  primary key (collection_id, memory_id)
);

create table if not exists public.interventions (
  id bigserial primary key,
  user_id text not null,
  reason text not null,
  message text not null,
  status text not null default 'pending',
  message_type text,
  feedback_score integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint interventions_status_check
    check (status in ('pending', 'shown', 'interacted', 'dismissed'))
);

create table if not exists public.intervention_feedback (
  id bigserial primary key,
  intervention_id bigint not null references public.interventions(id) on delete cascade,
  user_id text not null,
  explicit_score integer not null,
  created_at timestamptz not null default now(),
  constraint intervention_feedback_explicit_score_check
    check (explicit_score in (2, -2))
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists memories_updated_at on public.memories;
create trigger memories_updated_at
  before update on public.memories
  for each row execute function public.set_updated_at();

drop trigger if exists collections_updated_at on public.collections;
create trigger collections_updated_at
  before update on public.collections
  for each row execute function public.set_updated_at();

drop trigger if exists interventions_updated_at on public.interventions;
create trigger interventions_updated_at
  before update on public.interventions
  for each row execute function public.set_updated_at();

create index if not exists idx_memories_user_memory_at
  on public.memories(user_id, memory_at desc);

create index if not exists idx_memories_user_created
  on public.memories(user_id, created_at desc);

create index if not exists idx_collections_user_created
  on public.collections(user_id, created_at desc);

create index if not exists idx_collection_memories_memory_id
  on public.collection_memories(memory_id);

create index if not exists idx_interventions_user_pending_created
  on public.interventions(user_id, created_at desc)
  where status = 'pending';

create index if not exists idx_intervention_feedback_intervention_id
  on public.intervention_feedback(intervention_id);
