-- Moodot RDS PostgreSQL schema draft
-- ------------------------------------------------------------
-- This is a draft based on the current backend/worker code.
-- Before applying it to RDS, compare it with the real Supabase
-- schema exported from information_schema.
--
-- Note: Supabase has foreign keys to auth.users(id). RDS will not
-- have Supabase auth.users, because Cognito is the new auth source.
-- Keep user_id as the Cognito sub value and enforce ownership in the app.

create extension if not exists pgcrypto;
create extension if not exists "uuid-ossp";

create table if not exists public.emotion_categories (
  emotion_id integer generated by default as identity primary key,
  emotion varchar not null unique
);

insert into public.emotion_categories (emotion_id, emotion)
values
  (1, 'good'),
  (2, 'bad'),
  (3, 'sad'),
  (4, 'calm')
on conflict (emotion_id) do update
set emotion = excluded.emotion;

create table if not exists public.memories (
  id bigserial primary key,
  user_id uuid not null,
  title text,
  text text,
  image_url text,
  emotion_id integer not null references public.emotion_categories(emotion_id),
  with_whom text,
  location_lat double precision,
  location_lng double precision,
  location_label text,
  place_name text,
  location_type text,
  memory_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  processed boolean default false,
  text_ciphertext text,
  text_iv text,
  text_key_version smallint not null default 1
);

create table if not exists public.collections (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  note text,
  location text,
  start_date date,
  end_date date,
  cover_memory_id bigint references public.memories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid not null,
  constraint collections_title_check
    check (length(trim(title)) >= 1)
);

create table if not exists public.collection_memories (
  id uuid primary key default uuid_generate_v4(),
  collection_id uuid not null references public.collections(id) on delete cascade,
  memory_id bigint not null references public.memories(id) on delete cascade,
  position integer not null,
  created_at timestamptz not null default now(),
  constraint collection_memories_collection_id_memory_id_key
    unique (collection_id, memory_id)
);

create table if not exists public.interventions (
  id bigserial primary key,
  created_at timestamptz not null default now(),
  reason text not null,
  message text not null,
  status text not null default 'pending',
  user_id uuid not null,
  message_type text,
  feedback_score smallint,
  constraint interventions_status_check
    check (status in ('pending', 'shown', 'interacted', 'dismissed'))
);

create table if not exists public.intervention_feedback (
  id uuid primary key default gen_random_uuid(),
  intervention_id bigint not null references public.interventions(id) on delete cascade,
  user_id text not null,
  explicit_score integer,
  responded boolean,
  response_length integer,
  response_time_sec integer,
  created_at timestamptz default now(),
  constraint intervention_feedback_explicit_score_check
    check (explicit_score in (-2, 0, 2))
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists memories_updated_at on public.memories;
create trigger memories_updated_at
  before update on public.memories
  for each row execute function public.set_updated_at();

drop trigger if exists collections_updated_at on public.collections;
create trigger collections_updated_at
  before update on public.collections
  for each row execute function public.set_updated_at();

create index if not exists idx_memories_user_memory_at_desc
  on public.memories(user_id, memory_at desc);

create index if not exists idx_memories_unprocessed
  on public.memories(created_at desc)
  where processed = false;

create index if not exists idx_collections_user_created
  on public.collections(user_id, created_at desc);

create index if not exists idx_collection_memories_collection_id
  on public.collection_memories(collection_id);

create index if not exists idx_collection_memories_memory_id
  on public.collection_memories(memory_id);

create index if not exists idx_interventions_created_at
  on public.interventions(created_at desc);

create index if not exists idx_interventions_pending
  on public.interventions(created_at desc)
  where status = 'pending';

create index if not exists idx_intervention_feedback_intervention_id
  on public.intervention_feedback(intervention_id);
